# fly.toml app configuration file generated for firey-bot on 2024-05-15T00:49:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'firey-bot'
primary_region = 'atl'

[build]

[[services]]
 internal_port = 3000
 protocol = "tcp"

[[services.ports]]
  handlers = ["http"]
  port = 80

[[vm]]
  size = 'shared-cpu-1x'

  
