# fly.toml app configuration file generated for firey-bot on 2024-05-15T00:49:31-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'firey-bot'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 46271
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
