# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: FlyIO Deployment

on:
  push:
    branches: [ deploy ]

jobs:
  Deployment:
    runs-on: ubuntu-latest
    environment: flyiodeploy
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Setup FlyIO
      uses: superfly/flyctl-actions/setup-flyctl@master
    - name: install package
      run: npm ci
    - name: lint check
      run: npm run lint:check
    - name: Prisma Checker
      run: npx prisma generate
    - name: Type Check
      run: npm run build:check
    - name: Unit Test
      run: npm run test
    - name: Deploy FlyIO
      run: flyctl deploy --remote-only --ha=false --build-arg SENTRY_ORG=$SENTRY_ORG --build-arg SENTRY_PROJECT=$SENTRY_PROJECT --build-arg SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN
      env:
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        FLY_API_TOKEN: ${{ secrets.FLY_API_KEY }}
